### ISSUE TITLE
Python and Neovim - Question

### ISSUE THREAD

**Issue by hurricanehrndz** [mjlbach/nix-dotfiles#1]
Hi,

I just noticed your Neovim config changed a bit 3 months ago, and it looks like you are now using python3 with Neovim or am I wrong?

If you do, can you please share how you're getting the plugins installed... I can't seem to find it in your nix code.

Thanks in advance.

**Comment by mjlbach** [comment]
What do you mean "using python 3 with neovim"? I don't use any python remote plugin providers. What do you mean by installing plugins? I use packer for everything now (not nix).

**Comment by hurricanehrndz** [comment]
Just saw you were using neformat with black. As far as I know, black is a Python module only. Yes, excuse the mistake in terminology.

**Comment by hurricanehrndz** [comment]
PS I think your response clarifies it.

**Comment by mjlbach** [comment]
So long as black is on your system path, you can call it with neoformat

**Comment by hurricanehrndz** [comment]
That explains a lot --- that was going to be my next assumption.
