### ISSUE TITLE
Mjlbach's neovim config

### ISSUE THREAD

**Issue by Binxptr** [mjlbach/nix-dotfiles#6]
Hi, I see that you've updated the readme to say you don't use nix or nixos. Does that mean you're not going to be updating your neovim config either? I currently use yours, with a few tweaks and it works out really well for me :) Especially with no auto-completion which I'm trying to get used to

**Comment by mjlbach** [comment]
My much simpler dotfiles are now available here :) 

https://github.com/mjlbach/dotfiles

**Comment by Binxptr** [comment]
Oh, that's amazing! Thank you!
