### ISSUE TITLE
More info about ditching NixOS

### ISSUE THREAD

**Issue by harrysolovay** [mjlbach/nix-dotfiles#7]
Hi @mjlbach –– I don't want to impose, but I'm curious to hear more about your decision to stop using NixOS (if you have time). Thanks!

**Comment by mjlbach** [comment]
https://github.com/mjlbach/nix-dotfiles

**Comment by harrysolovay** [comment]
These updates to the readme are GOLD. Really great description. Thank you @mjlbach!
